webtalk_init -webtalk_dir D:\\projects\\itmo\\io_lab2\\io_lab2\\io_lab2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-12-13 02:55:47" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "m2hm79lclkt0dvkboclke2bsfv" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3311 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1513116898103" -context "sdk\\\\bsp/1513116898103"
webtalk_add_data -client sdk -key hwid -value "1512902339187" -context "sdk\\\\bsp/1513116898103"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1513116898103"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1513116898103"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1513116898103"
webtalk_add_data -client sdk -key uid -value "1513116907449" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key hwid -value "1512902339187" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key bspid -value "1513116898103" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key projSize -value "82.47265625" -context "sdk\\\\application/1513116907449"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1513122947797"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1513122947797"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1513122947797"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1513122947797"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1513122947797"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1513122947797"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1513122947797"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1513122947797"
webtalk_transmit -clientid 1144049136 -regid "" -xml D:\\projects\\itmo\\io_lab2\\io_lab2\\io_lab2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\projects\\itmo\\io_lab2\\io_lab2\\io_lab2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\projects\\itmo\\io_lab2\\io_lab2\\io_lab2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
