# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr.xdc

# Block Designs: bd/uc_system/uc_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system || ORIG_REF_NAME==uc_system}]

# IP: bd/uc_system/ip/uc_system_microblaze_0_0/uc_system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_microblaze_0_0 || ORIG_REF_NAME==uc_system_microblaze_0_0}]

# IP: bd/uc_system/ip/uc_system_clk_wiz_0_0/uc_system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_clk_wiz_0_0 || ORIG_REF_NAME==uc_system_clk_wiz_0_0}]

# IP: bd/uc_system/ip/uc_system_proc_sys_reset_0_0/uc_system_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_proc_sys_reset_0_0 || ORIG_REF_NAME==uc_system_proc_sys_reset_0_0}]

# IP: bd/uc_system/ip/uc_system_axi_timer_0_0/uc_system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_axi_timer_0_0 || ORIG_REF_NAME==uc_system_axi_timer_0_0}]

# IP: bd/uc_system/ip/uc_system_axi_gpio_0_0/uc_system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_axi_gpio_0_0 || ORIG_REF_NAME==uc_system_axi_gpio_0_0}]

# IP: bd/uc_system/ip/uc_system_dlmb_v10_0/uc_system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_dlmb_v10_0 || ORIG_REF_NAME==uc_system_dlmb_v10_0}]

# IP: bd/uc_system/ip/uc_system_ilmb_v10_0/uc_system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_ilmb_v10_0 || ORIG_REF_NAME==uc_system_ilmb_v10_0}]

# IP: bd/uc_system/ip/uc_system_dlmb_bram_if_cntlr_0/uc_system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==uc_system_dlmb_bram_if_cntlr_0}]

# IP: bd/uc_system/ip/uc_system_ilmb_bram_if_cntlr_0/uc_system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==uc_system_ilmb_bram_if_cntlr_0}]

# IP: bd/uc_system/ip/uc_system_lmb_bram_0/uc_system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_lmb_bram_0 || ORIG_REF_NAME==uc_system_lmb_bram_0}]

# IP: bd/uc_system/ip/uc_system_microblaze_core_axi_periph_0/uc_system_microblaze_core_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_microblaze_core_axi_periph_0 || ORIG_REF_NAME==uc_system_microblaze_core_axi_periph_0}]

# IP: bd/uc_system/ip/uc_system_xbar_1/uc_system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_xbar_1 || ORIG_REF_NAME==uc_system_xbar_1}]

# IP: bd/uc_system/ip/uc_system_axi_bram_ctrl_0_0/uc_system_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==uc_system_axi_bram_ctrl_0_0}]

# IP: bd/uc_system/ip/uc_system_axi_uartlite_0_0/uc_system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_axi_uartlite_0_0 || ORIG_REF_NAME==uc_system_axi_uartlite_0_0}]

# IP: bd/uc_system/ip/uc_system_BRAM_Interconnect_0_0/uc_system_BRAM_Interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_BRAM_Interconnect_0_0 || ORIG_REF_NAME==uc_system_BRAM_Interconnect_0_0}]

# IP: bd/uc_system/ip/uc_system_Timer_0_1/uc_system_Timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_Timer_0_1 || ORIG_REF_NAME==uc_system_Timer_0_1}]

# IP: bd/uc_system/ip/uc_system_Timer_1_0/uc_system_Timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_Timer_1_0 || ORIG_REF_NAME==uc_system_Timer_1_0}]

# IP: bd/uc_system/ip/uc_system_Output_Compare_0_0/uc_system_Output_Compare_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_Output_Compare_0_0 || ORIG_REF_NAME==uc_system_Output_Compare_0_0}]

# IP: bd/uc_system/ip/uc_system_auto_pc_0/uc_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uc_system_auto_pc_0 || ORIG_REF_NAME==uc_system_auto_pc_0}]

# XDC: bd/uc_system/uc_system_ooc.xdc
