# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Laptop/Documents/projects/io_lab2/io_lab2/io_lab2.srcs/sources_1/bd/uc_system/ip/uc_system_xbar_1/uc_system_xbar_1.xci
# IP: The module: 'uc_system_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Laptop/Documents/projects/io_lab2/io_lab2/io_lab2.srcs/sources_1/bd/uc_system/ip/uc_system_xbar_1/uc_system_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uc_system_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Laptop/Documents/projects/io_lab2/io_lab2/io_lab2.srcs/sources_1/bd/uc_system/ip/uc_system_xbar_1/uc_system_xbar_1.xci
# IP: The module: 'uc_system_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Laptop/Documents/projects/io_lab2/io_lab2/io_lab2.srcs/sources_1/bd/uc_system/ip/uc_system_xbar_1/uc_system_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uc_system_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
